version: "3.8"

services:
  mongodb:
    image: mongo:latest
    container_name: autohauscrm_mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongodb_data:/data/db
    networks:
      - autohauscrm_network
    ports:
      - "27017:27017"

volumes:
  mongodb_data:
    driver: local

networks:
  autohauscrm_network:
    driver: bridge
